In [4]:
import numpy as np

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
x=np.arange(1,20,3)
print(x)

[ 1  4  7 10 13 16 19]


In [47]:
x=np.linspace(1,20,5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [21]:
#array filling for 1D

y=np.full((7),20)
print(y)
#To know the dimension of array
print(y.ndim)

print("-----------")

#array filling for 2D

z=np.full((2,3),7)
print(z)
print(z.ndim)

print("-----------")
#array filling for 2D

e=np.full((2,3,3),9)
print(e)
print(e.ndim)

[20 20 20 20 20 20 20]
1
-----------
[[7 7 7]
 [7 7 7]]
2
-----------
[[[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]]
3


In [24]:
#To find shape
arr=np.array([[7, 7 ,7],[7, 7, 7]])
print(arr.shape)

(2, 3)


In [30]:
#Identity matrix

e=np.eye(3)
print(e)

print("-----------")

#To get random values
arr=np.random.random((2,2))
print(arr)
print(arr.size) #will give number of elements in array
print(len(arr)) #will calcualte only rows

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------
[[0.36354354 0.23494708]
 [0.59162642 0.41388893]]
4
2


In [40]:
#Math operations
x=[20,21,10]
y=[9,25,22]
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))
print(np.sqrt(y))

#Accessing
print(x[1])

#Adding two index values

print(x[1]+y[0])

[29 46 32]
[ 11  -4 -12]
[180 525 220]
[2.22222222 0.84       0.45454545]
[4.47213595 4.58257569 3.16227766]
[3.         5.         4.69041576]
21
30


In [17]:
#Copy method

arr=[7,7,7]
copy_arr=arr.copy()
arr[0]=6
print(f"Original Array: {arr}")
print(f"Copied Array: {copy_arr}")

#View Method

arr=np.array([7,7,7])
view_arr=arr.view()
arr[0]=6
print(f"Original Array: {arr}")
print(f"Viewed Array: {view_arr}")

#Shape Method

arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[2,5,8,6]])
arr.shape
print(f"Array Shape: {arr.shape}")

#Reshaping Method 
arr=np.array([[2,3,4,5,6,7,8,9,1]])
print(f"Reshaping array:{ arr.reshape(3,3)}")

Original Array: [6, 7, 7]
Copied Array: [7, 7, 7]
Original Array: [6 7 7]
Viewed Array: [6 7 7]
Array Shape: (3, 4)
Reshaping array:[[2 3 4]
 [5 6 7]
 [8 9 1]]
